/**
 * UX Vision Orchestrator
 * Reads every PNG in ux-screenshots/, sends each to the Claude API with a
 * strict UX critique prompt, then writes:
 *   - UX_FIXES_SPEC.md  → Markdown checklists of Tailwind/React fixes
 *   - UX_STATUS.txt     → "PERFECT" if every screen is flawless, else "NEEDS_FIXES"
 */

import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Anthropic from '@anthropic-ai/sdk';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCREENSHOTS_DIR = path.resolve(__dirname, '../ux-screenshots');
const SPEC_OUT    = path.resolve(__dirname, '../UX_FIXES_SPEC.md');
const STATUS_OUT  = path.resolve(__dirname, '../UX_STATUS.txt');

const MODEL = 'claude-haiku-4-5-20251001';

const CRITIQUE_PROMPT = `You are a Senior Frontend UI/UX Engineer performing a rigorous design QA pass.

Examine this screenshot of a React/Tailwind dark-themed game called "Bandwidth" (a corporate RPG with a zinc-900 palette).

Identify ONLY real, actionable issues — do NOT flag intentional dark/satirical copy or dev-mode placeholders.

Specifically look for:
1. Text overflow, truncation, or elements clipped by containers
2. Low contrast text that fails WCAG AA (especially light gray on dark zinc backgrounds)
3. Missing hover/focus states on interactive buttons
4. Inconsistent spacing or misaligned elements
5. Unlabeled or ambiguous UI numbers/timers
6. Scrollbars appearing where content should fit the viewport
7. Modal/overlay z-index or backdrop issues

Output format — STRICT:
- If you find issues: output a Markdown checklist. Every item MUST start with "- [ ] Task:" and include the specific Tailwind class change needed.
- If the screen is flawless with no actionable issues: output exactly the string "STATUS: PERFECT" and nothing else.

Do NOT output any preamble, summary, or closing remarks — only the checklist or "STATUS: PERFECT".`;

async function run() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('❌  ANTHROPIC_API_KEY is not set. Run: export ANTHROPIC_API_KEY=...');
    process.exit(1);
  }

  if (!fs.existsSync(SCREENSHOTS_DIR)) {
    console.error(`❌  Screenshots directory not found: ${SCREENSHOTS_DIR}`);
    console.error('    Run the Playwright crawler first: npx playwright test tests/ux-matrix-crawler.spec.ts');
    process.exit(1);
  }

  const files = fs.readdirSync(SCREENSHOTS_DIR)
    .filter(f => f.endsWith('.png'))
    .sort();

  if (files.length === 0) {
    console.error('❌  No PNG screenshots found in', SCREENSHOTS_DIR);
    process.exit(1);
  }

  console.log(`\n🔍  Analysing ${files.length} screenshots with ${MODEL}...\n`);

  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

  let allPerfect = true;
  let specContent = `# UX Fixes Specification\n_Generated by ux-critic.js on ${new Date().toISOString()}_\n\n`;

  for (const file of files) {
    process.stdout.write(`  → ${file} ... `);
    const imageBuffer = fs.readFileSync(path.join(SCREENSHOTS_DIR, file));
    const base64Image = imageBuffer.toString('base64');

    let responseText = '';
    try {
      const response = await anthropic.messages.create({
        model: MODEL,
        max_tokens: 1200,
        messages: [{
          role: 'user',
          content: [
            { type: 'image', source: { type: 'base64', media_type: 'image/png', data: base64Image } },
            { type: 'text', text: CRITIQUE_PROMPT },
          ],
        }],
      });
      responseText = response.content[0].type === 'text' ? response.content[0].text.trim() : '';
    } catch (err) {
      responseText = `- [ ] Task: API error for ${file} — ${(err instanceof Error ? err.message : String(err))}`;
    }

    const isPerfect = responseText === 'STATUS: PERFECT';
    console.log(isPerfect ? '✅  PERFECT' : '⚠️   HAS ISSUES');

    if (!isPerfect) {
      allPerfect = false;
      specContent += `## ${file}\n\n${responseText}\n\n---\n\n`;
    } else {
      specContent += `## ${file}\n\n✅ No issues found.\n\n---\n\n`;
    }
  }

  fs.writeFileSync(SPEC_OUT,   specContent,                     'utf8');
  fs.writeFileSync(STATUS_OUT, allPerfect ? 'PERFECT' : 'NEEDS_FIXES', 'utf8');

  console.log(`\n${ allPerfect ? '🎉  All screens PERFECT' : '📋  Issues found' }`);
  console.log(`   UX_FIXES_SPEC.md → ${SPEC_OUT}`);
  console.log(`   UX_STATUS.txt    → ${STATUS_OUT}\n`);
}

run().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
